/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.LoginController;
import Model.UserModel;

/**
 *
 * @author LENOVO
 */
public class Login extends javax.swing.JFrame {

    private final UserModel userModel;
    private LoginController loginController;

    public Login(UserModel userModel, LoginController loginController) {
        initComponents();
        this.userModel = userModel;
        setLoginController(loginController);
    }

    // Metode setLoginController
    public void setLoginController(LoginController loginController) {
        this.loginController = loginController;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelNameKaraoke = new javax.swing.JLabel();
        jLabelDescription = new javax.swing.JLabel();
        jLabelUsername = new javax.swing.JLabel();
        jLabelPassword = new javax.swing.JLabel();
        jLabelRole = new javax.swing.JLabel();
        jComboBoxRole = new javax.swing.JComboBox<>();
        fTextFieldUsername = new source_ui.FTextField();
        fPasswordFieldPassword = new source_ui.FPasswordField();
        fButtonToRegister = new source_ui.FButton();
        fButtonToLogin = new source_ui.FButton();
        jTextField1 = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        jButtonLogin = new javax.swing.JButton();
        jButtonToRegister = new javax.swing.JButton();
        jLabelBackground1 = new javax.swing.JLabel();
        jLabelBackground2 = new javax.swing.JLabel();
        jLabelBackground3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login Page");
        setBackground(new java.awt.Color(39, 0, 93));
        setPreferredSize(new java.awt.Dimension(1080, 608));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabelNameKaraoke.setFont(new java.awt.Font("Poppins", 1, 70)); // NOI18N
        jLabelNameKaraoke.setForeground(new java.awt.Color(228, 241, 255));
        jLabelNameKaraoke.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelNameKaraoke.setText("UVUtopia");
        getContentPane().add(jLabelNameKaraoke);
        jLabelNameKaraoke.setBounds(30, 20, 350, 70);

        jLabelDescription.setFont(new java.awt.Font("Poppins", 1, 20)); // NOI18N
        jLabelDescription.setForeground(new java.awt.Color(228, 241, 255));
        jLabelDescription.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabelDescription.setText("In a world of noise, \nfind your melody \nwith us.");
        getContentPane().add(jLabelDescription);
        jLabelDescription.setBounds(30, 90, 460, 30);

        jLabelUsername.setFont(new java.awt.Font("Poppins", 1, 20)); // NOI18N
        jLabelUsername.setForeground(new java.awt.Color(228, 241, 255));
        jLabelUsername.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelUsername.setText("Username");
        getContentPane().add(jLabelUsername);
        jLabelUsername.setBounds(640, 200, 170, 30);

        jLabelPassword.setFont(new java.awt.Font("Poppins", 1, 20)); // NOI18N
        jLabelPassword.setForeground(new java.awt.Color(228, 241, 255));
        jLabelPassword.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelPassword.setText("Password");
        getContentPane().add(jLabelPassword);
        jLabelPassword.setBounds(640, 290, 140, 30);

        jLabelRole.setFont(new java.awt.Font("Poppins", 1, 20)); // NOI18N
        jLabelRole.setForeground(new java.awt.Color(228, 241, 255));
        jLabelRole.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelRole.setText("Role");
        getContentPane().add(jLabelRole);
        jLabelRole.setBounds(640, 110, 70, 30);

        jComboBoxRole.setBackground(new java.awt.Color(174, 210, 255));
        jComboBoxRole.setFont(new java.awt.Font("Poppins", 1, 20)); // NOI18N
        jComboBoxRole.setForeground(new java.awt.Color(148, 0, 255));
        jComboBoxRole.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "User", "Staff" }));
        getContentPane().add(jComboBoxRole);
        jComboBoxRole.setBounds(640, 150, 260, 30);

        fTextFieldUsername.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        fTextFieldUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fTextFieldUsernameActionPerformed(evt);
            }
        });
        getContentPane().add(fTextFieldUsername);
        fTextFieldUsername.setBounds(640, 240, 260, 48);
        getContentPane().add(fPasswordFieldPassword);
        fPasswordFieldPassword.setBounds(640, 330, 270, 50);

        fButtonToRegister.setText("Register");
        fButtonToRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fButtonToRegisterActionPerformed(evt);
            }
        });
        getContentPane().add(fButtonToRegister);
        fButtonToRegister.setBounds(790, 410, 110, 40);

        fButtonToLogin.setText("Login");
        fButtonToLogin.setMaximumSize(new java.awt.Dimension(120, 36));
        fButtonToLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fButtonToLoginActionPerformed(evt);
            }
        });
        getContentPane().add(fButtonToLogin);
        fButtonToLogin.setBounds(640, 410, 110, 40);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1);
        jTextField1.setBounds(894, 191, 72, 26);

        jPasswordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jPasswordField1);
        jPasswordField1.setBounds(925, 254, 72, 26);

        jButtonLogin.setText("Login");
        jButtonLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLoginActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonLogin);
        jButtonLogin.setBounds(940, 330, 76, 27);

        jButtonToRegister.setText("Register");
        jButtonToRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonToRegisterActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonToRegister);
        jButtonToRegister.setBounds(910, 110, 76, 27);

        jLabelBackground1.setBackground(new java.awt.Color(39, 0, 93));
        jLabelBackground1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/images/backgroundImage.png"))); // NOI18N
        jLabelBackground1.setText("jLabel2");
        getContentPane().add(jLabelBackground1);
        jLabelBackground1.setBounds(540, 340, 540, 270);

        jLabelBackground2.setBackground(new java.awt.Color(39, 0, 93));
        jLabelBackground2.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabelBackground2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/images/backgroundImage.png"))); // NOI18N
        jLabelBackground2.setText("jLabel2");
        getContentPane().add(jLabelBackground2);
        jLabelBackground2.setBounds(540, 0, 540, 340);

        jLabelBackground3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/images/loginImage.png"))); // NOI18N
        jLabelBackground3.setText("jLabel5");
        jLabelBackground3.setPreferredSize(new java.awt.Dimension(540, 608));
        getContentPane().add(jLabelBackground3);
        jLabelBackground3.setBounds(0, 0, 540, 610);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButtonLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLoginActionPerformed
        // TODO add your handling code here:
        String role = jComboBoxRole.getSelectedItem().toString();
        String username = jTextField1.getText();
        String password = new String(jPasswordField1.getPassword());
        
        // Memanggil metode processLogin pada LoginController
        boolean loginSuccessful = loginController.processLogin(role, username, password);
        
        if (loginSuccessful) {
            // Jika login berhasil, pindah ke halaman paket
            loginController.switchToPaket(username);
        } else {
            // Jika login gagal, tambahkan logika lainnya jika diperlukan
            System.out.println("Login Gagal!");
        }
    }//GEN-LAST:event_jButtonLoginActionPerformed

    private void jButtonToRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonToRegisterActionPerformed
        // TODO add your handling code here:
        if (loginController != null) {
            loginController.switchToRegister();
        } else {
            System.err.println("LoginController is null. Make sure it is set before calling switchToRegister.");
        }
    }//GEN-LAST:event_jButtonToRegisterActionPerformed

    private void jPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField1ActionPerformed

    private void fButtonToRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fButtonToRegisterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fButtonToRegisterActionPerformed

    private void fTextFieldUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fTextFieldUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fTextFieldUsernameActionPerformed

    private void fButtonToLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fButtonToLoginActionPerformed
        // TODO add your handling code here:
         String role = jComboBoxRole.getSelectedItem().toString();
        String username = jTextField1.getText();
        String password = new String(jPasswordField1.getPassword());
        
        // Memanggil metode processLogin pada LoginController
        boolean loginSuccessful = loginController.processLogin(role, username, password);
        
        if (loginSuccessful) {
            // Jika login berhasil, pindah ke halaman paket
            loginController.switchToPaket(username);
        } else {
            // Jika login gagal, tambahkan logika lainnya jika diperlukan
            System.out.println("Login Gagal!");
        }
    }//GEN-LAST:event_fButtonToLoginActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private source_ui.FButton fButtonToLogin;
    private source_ui.FButton fButtonToRegister;
    private source_ui.FPasswordField fPasswordFieldPassword;
    private source_ui.FTextField fTextFieldUsername;
    private javax.swing.JButton jButtonLogin;
    private javax.swing.JButton jButtonToRegister;
    private javax.swing.JComboBox<String> jComboBoxRole;
    private javax.swing.JLabel jLabelBackground1;
    private javax.swing.JLabel jLabelBackground2;
    private javax.swing.JLabel jLabelBackground3;
    private javax.swing.JLabel jLabelDescription;
    private javax.swing.JLabel jLabelNameKaraoke;
    private javax.swing.JLabel jLabelPassword;
    private javax.swing.JLabel jLabelRole;
    private javax.swing.JLabel jLabelUsername;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
