/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

/**
 *
 * @author LENOVO
 */
import Controller.PaketController;
import Model.PaketModel;
import Model.Ruangan;
import javax.swing.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.List;

public class Paket extends javax.swing.JFrame {

    private PaketModel paketModel;
    private PaketController paketController;

    public Paket(PaketModel paketModel) {
        initComponents();
        this.paketModel = paketModel;
        setPaketController(new PaketController(paketModel, this));
    }

    public void setPaketController(PaketController paketController) {
        this.paketController = paketController;
    }

    public javax.swing.JComboBox<String> getjComboBoxDurasi() {
        return jComboBoxDurasi;
    }

    public javax.swing.JComboBox<String> getjComboBoxRuangan() {
        return jComboBoxRuangan;
    }

    public javax.swing.JLabel getjLabelTotal() {
        return jLabelTotal;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        jFrame1 = new javax.swing.JFrame();
        jComboBoxDurasi = new javax.swing.JComboBox<>();
        jLabelDurasi = new javax.swing.JLabel();
        jLabelRuangan = new javax.swing.JLabel();
        jComboBoxRuangan = new javax.swing.JComboBox<>();
        jLabelTotal = new javax.swing.JLabel();
        jButtonNext = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jInternalFrame1.setVisible(true);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jComboBoxDurasi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1 jam", "2 jam ", "3 jam ", "4 jam" }));

        jLabelDurasi.setText("Durasi");

        jLabelRuangan.setText("Ruangan");

        jComboBoxRuangan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Small \t4 – 5 orang\t= 50.000/jam. ", "Medium \t6 – 8 orang\t= 60.000/jam. ", "Large \t8 -10 orang\t= 80.000/jam. ", "Deluxe \t10 – 14 orang\t= 100.000/jam.", "VVIP  \t10-14 orang\t= 200.000/jam." }));

        jLabelTotal.setText("Total");

        jButtonNext.setText("Next");
        jButtonNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNextActionPerformed(evt);
            }
        });

        jLabel1.setText("Selamat Datang, ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jButtonNext)
                    .addComponent(jLabelTotal)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelDurasi)
                            .addComponent(jLabelRuangan))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBoxRuangan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBoxDurasi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(34, 34, 34))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(jLabel1)
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelRuangan)
                    .addComponent(jComboBoxRuangan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelDurasi)
                    .addComponent(jComboBoxDurasi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addComponent(jLabelTotal)
                .addGap(30, 30, 30)
                .addComponent(jButtonNext)
                .addContainerGap(269, Short.MAX_VALUE))
        );

        setBounds(0, 0, 1096, 616);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNextActionPerformed
        // Get the selected duration
        String durasiSelected = jComboBoxDurasi.getSelectedItem().toString();
        int durasi = Integer.parseInt(durasiSelected.split(" ")[0]);

        // Create an instance of MediaPlayer and pass the duration
        MediaPlayer mediaPlayerFrame = new MediaPlayer(1);

        // Set the visibility of the current frame to false
        this.setVisible(false);

        // Set the default close operation for the current frame
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);

        // Make the MediaPlayer frame visible
        mediaPlayerFrame.setVisible(true);
    }//GEN-LAST:event_jButtonNextActionPerformed
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                // Buat objek PaketModel dan inisialisasi sesuai kebutuhan
                PaketModel paketModel = new PaketModel();

                // Buat objek Paket dan kirimkan objek PaketModel
                new Paket(paketModel).setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonNext;
    private javax.swing.JComboBox<String> jComboBoxDurasi;
    private javax.swing.JComboBox<String> jComboBoxRuangan;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelDurasi;
    private javax.swing.JLabel jLabelRuangan;
    private javax.swing.JLabel jLabelTotal;
    // End of variables declaration//GEN-END:variables
}
