package View;

import Controller.PaketController;
import Model.PaketModel;
import Model.TransaksiModel;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.util.Calendar;
import java.util.Date;

public class Paket extends javax.swing.JFrame {

    // Variabel username sebagai atribut kelas
    private String username;
    private PaketModel paketModel;
    private TransaksiModel transaksiModel; // Tambahkan atribut TransaksiModel
    private PaketController paketController;

    // Ubah konstruktor untuk menerima TransaksiModel
    public Paket(PaketModel paketModel, String username, TransaksiModel transaksiModel) {
        initComponents();
        this.paketModel = paketModel;
        this.username = username;
        this.transaksiModel = transaksiModel; // Inisialisasi atribut TransaksiModel
        setPaketController(new PaketController(paketModel, this, transaksiModel)); // Teruskan TransaksiModel ke PaketController
        paketController.setWelcomeLabel(username);
    }

    public void setPaketController(PaketController paketController) {
        this.paketController = paketController;
    }

    public javax.swing.JComboBox<String> getjComboBoxDurasi() {
        return jComboBoxDurasi;
    }

    public javax.swing.JComboBox<String> getjComboBoxRuangan() {
        return jComboBoxRuangan;
    }

    public javax.swing.JLabel getjLabelTotal() {
        return jLabelTotal;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        jFrame1 = new javax.swing.JFrame();
        jComboBoxDurasi = new javax.swing.JComboBox<>();
        jLabelDurasi = new javax.swing.JLabel();
        jLabelRuangan = new javax.swing.JLabel();
        jComboBoxRuangan = new javax.swing.JComboBox<>();
        jLabelTotal = new javax.swing.JLabel();
        jButtonNext = new javax.swing.JButton();
        jLabelWelcome = new javax.swing.JLabel();

        jInternalFrame1.setVisible(true);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jComboBoxDurasi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1 jam", "2 jam ", "3 jam ", "4 jam" }));

        jLabelDurasi.setText("Durasi");

        jLabelRuangan.setText("Ruangan");

        jComboBoxRuangan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Small \t4 – 5 orang\t= 50.000/jam. ", "Medium \t6 – 8 orang\t= 60.000/jam. ", "Large \t8 -10 orang\t= 80.000/jam. ", "Deluxe \t10 – 14 orang\t= 100.000/jam.", "VVIP  \t10-14 orang\t= 200.000/jam." }));

        jLabelTotal.setText("Total");

        jButtonNext.setText("Next");
        jButtonNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNextActionPerformed(evt);
            }
        });

        jLabelWelcome.setText("Selamat Datang, ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelWelcome)
                    .addComponent(jButtonNext)
                    .addComponent(jLabelTotal)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelDurasi)
                            .addComponent(jLabelRuangan))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBoxRuangan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBoxDurasi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(34, 34, 34))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(jLabelWelcome)
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelRuangan)
                    .addComponent(jComboBoxRuangan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelDurasi)
                    .addComponent(jComboBoxDurasi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addComponent(jLabelTotal)
                .addGap(30, 30, 30)
                .addComponent(jButtonNext)
                .addContainerGap(269, Short.MAX_VALUE))
        );

        setBounds(0, 0, 1096, 616);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNextActionPerformed
        String durasiSelected = jComboBoxDurasi.getSelectedItem().toString();
        int durasi = Integer.parseInt(durasiSelected.split(" ")[0]);

        // Mendapatkan tanggal hari ini
        Date tanggalTransaksi = Calendar.getInstance().getTime();
        
        // Mendapatkan username dari atribut kelas
        String username = this.username;

        // Mendapatkan total harga dari model transaksi
        int totalHarga = paketController.getTransaksiModel().getTotalHarga();

        paketController.saveTransaksi(tanggalTransaksi, username, durasi, totalHarga);
        // Memanggil metode switchToTransaksi pada PaketController
        paketController.switchToTransaksi();
    }//GEN-LAST:event_jButtonNextActionPerformed

    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                // Buat objek PaketModel dan inisialisasi sesuai kebutuhan
                PaketModel paketModel = new PaketModel();

                // Buat objek TransaksiModel
                TransaksiModel transaksiModel = new TransaksiModel();

                // Buat objek Paket dan kirimkan objek PaketModel, nama pengguna, dan objek TransaksiModel
                new Paket(paketModel, "NamaPengguna", transaksiModel).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonNext;
    private javax.swing.JComboBox<String> jComboBoxDurasi;
    private javax.swing.JComboBox<String> jComboBoxRuangan;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabelDurasi;
    private javax.swing.JLabel jLabelRuangan;
    private javax.swing.JLabel jLabelTotal;
    private javax.swing.JLabel jLabelWelcome;
    // End of variables declaration//GEN-END:variables

    public javax.swing.JLabel getjLabelWelcome() {
        return jLabelWelcome;
    }
}
