/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.LoginController;
import Controller.RegisterController;
import Model.UserModel;

/**
 *
 * @author LENOVO
 */
public class Register extends javax.swing.JFrame {

    private UserModel userModel;
    private RegisterController registerController;

    public Register(UserModel userModel, RegisterController registerController) {
        initComponents();
        this.userModel = userModel;
        setRegisterController(registerController);
        registerController.setRegisterView(this); 
    }

    public void setRegisterController(RegisterController registerController) {
        this.registerController = registerController;
    }

//    REGISTER
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelRole = new javax.swing.JLabel();
        jLabelUsername = new javax.swing.JLabel();
        jLabelTelepon = new javax.swing.JLabel();
        jLabelPassword = new javax.swing.JLabel();
        jLabelConfirmPassword = new javax.swing.JLabel();
        jComboBoxRole = new javax.swing.JComboBox<>();
        fTextFieldUsername = new source_ui.FTextField();
        fTextFieldTelepon = new source_ui.FTextField();
        fPasswordFieldPassword = new source_ui.FPasswordField();
        fPasswordFieldConfirmPassword = new source_ui.FPasswordField();
        jTextFieldTelepon = new javax.swing.JTextField();
        jTextFieldUsername = new javax.swing.JTextField();
        fButtonToLogin = new source_ui.FButton();
        fButtonToRegister = new source_ui.FButton();
        jPasswordField1 = new javax.swing.JPasswordField();
        jButtonRegister = new javax.swing.JButton();
        jPasswordField2 = new javax.swing.JPasswordField();
        jButtonToLogin = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1080, 608));
        setResizable(false);
        setSize(new java.awt.Dimension(1080, 608));
        getContentPane().setLayout(null);

        jLabelRole.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        jLabelRole.setForeground(new java.awt.Color(225, 241, 255));
        jLabelRole.setText("Role");
        getContentPane().add(jLabelRole);
        jLabelRole.setBounds(350, 60, 80, 30);

        jLabelUsername.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        jLabelUsername.setForeground(new java.awt.Color(228, 241, 255));
        jLabelUsername.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelUsername.setText("Username");
        getContentPane().add(jLabelUsername);
        jLabelUsername.setBounds(340, 120, 120, 30);

        jLabelTelepon.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        jLabelTelepon.setForeground(new java.awt.Color(228, 241, 255));
        jLabelTelepon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTelepon.setText("Nomor Telepon");
        getContentPane().add(jLabelTelepon);
        jLabelTelepon.setBounds(340, 190, 170, 30);

        jLabelPassword.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        jLabelPassword.setForeground(new java.awt.Color(228, 241, 255));
        jLabelPassword.setText("Password");
        getContentPane().add(jLabelPassword);
        jLabelPassword.setBounds(360, 260, 120, 30);

        jLabelConfirmPassword.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        jLabelConfirmPassword.setForeground(new java.awt.Color(228, 241, 255));
        jLabelConfirmPassword.setText("Confirm Password");
        getContentPane().add(jLabelConfirmPassword);
        jLabelConfirmPassword.setBounds(360, 330, 210, 30);

        jComboBoxRole.setBackground(new java.awt.Color(174, 210, 255));
        jComboBoxRole.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        jComboBoxRole.setForeground(new java.awt.Color(39, 0, 93));
        jComboBoxRole.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "User", "Staff" }));
        jComboBoxRole.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxRoleActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBoxRole);
        jComboBoxRole.setBounds(350, 90, 380, 29);

        fTextFieldUsername.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        fTextFieldUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fTextFieldUsernameActionPerformed(evt);
            }
        });
        getContentPane().add(fTextFieldUsername);
        fTextFieldUsername.setBounds(350, 150, 380, 40);

        fTextFieldTelepon.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        fTextFieldTelepon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fTextFieldTeleponActionPerformed(evt);
            }
        });
        getContentPane().add(fTextFieldTelepon);
        fTextFieldTelepon.setBounds(350, 220, 380, 40);
        getContentPane().add(fPasswordFieldPassword);
        fPasswordFieldPassword.setBounds(350, 290, 370, 39);

        fPasswordFieldConfirmPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fPasswordFieldConfirmPasswordActionPerformed(evt);
            }
        });
        getContentPane().add(fPasswordFieldConfirmPassword);
        fPasswordFieldConfirmPassword.setBounds(350, 360, 370, 39);

        jTextFieldTelepon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTeleponActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldTelepon);
        jTextFieldTelepon.setBounds(791, 140, 72, 26);

        jTextFieldUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldUsernameActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldUsername);
        jTextFieldUsername.setBounds(791, 108, 72, 26);

        fButtonToLogin.setText("Login");
        fButtonToLogin.setFont(new java.awt.Font("Poppins", 1, 20)); // NOI18N
        fButtonToLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fButtonToLoginActionPerformed(evt);
            }
        });
        getContentPane().add(fButtonToLogin);
        fButtonToLogin.setBounds(320, 440, 190, 50);

        fButtonToRegister.setText("Register");
        fButtonToRegister.setFont(new java.awt.Font("Poppins", 1, 20)); // NOI18N
        fButtonToRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fButtonToRegisterActionPerformed(evt);
            }
        });
        getContentPane().add(fButtonToRegister);
        fButtonToRegister.setBounds(570, 440, 190, 50);
        getContentPane().add(jPasswordField1);
        jPasswordField1.setBounds(791, 172, 72, 26);

        jButtonRegister.setText("Register");
        jButtonRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegisterActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonRegister);
        jButtonRegister.setBounds(790, 242, 77, 27);
        getContentPane().add(jPasswordField2);
        jPasswordField2.setBounds(791, 204, 72, 26);

        jButtonToLogin.setText("Login");
        jButtonToLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonToLoginActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonToLogin);
        jButtonToLogin.setBounds(791, 281, 76, 27);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/images/backgroundRegister.png"))); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(320, 50, 440, 370);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/images/backgroundImage.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 330, 600, 280);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/images/backgroundImage.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 600, 330);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/images/backgroundImage.png"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(600, 0, 480, 330);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/images/backgroundImage.png"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(600, 330, 480, 280);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldUsernameActionPerformed

    private void jButtonRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegisterActionPerformed
        // TODO add your handling code here:
        String role = jComboBoxRole.getSelectedItem().toString();
        String username = jTextFieldUsername.getText();
        String telepon = jTextFieldTelepon.getText();
        String password = new String(jPasswordField1.getPassword());
        String confirmPassword = new String(jPasswordField2.getPassword());
        registerController.processRegister(role, username, telepon, password, confirmPassword);

    }//GEN-LAST:event_jButtonRegisterActionPerformed

    private void jTextFieldTeleponActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTeleponActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTeleponActionPerformed

    private void jButtonToLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonToLoginActionPerformed
        // TODO add your handling code here:

        if (registerController != null) {
            registerController.switchToLogin();
        } else {
            System.err.println("RegisterController is null. Make sure it is set before calling switchToLogin.");
        }
    }//GEN-LAST:event_jButtonToLoginActionPerformed

    private void fTextFieldUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fTextFieldUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fTextFieldUsernameActionPerformed

    private void fTextFieldTeleponActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fTextFieldTeleponActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fTextFieldTeleponActionPerformed

    private void fButtonToRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fButtonToRegisterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fButtonToRegisterActionPerformed

    private void jComboBoxRoleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxRoleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxRoleActionPerformed

    private void fButtonToLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fButtonToLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fButtonToLoginActionPerformed

    private void fPasswordFieldConfirmPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fPasswordFieldConfirmPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fPasswordFieldConfirmPasswordActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private source_ui.FButton fButtonToLogin;
    private source_ui.FButton fButtonToRegister;
    private source_ui.FPasswordField fPasswordFieldConfirmPassword;
    private source_ui.FPasswordField fPasswordFieldPassword;
    private source_ui.FTextField fTextFieldTelepon;
    private source_ui.FTextField fTextFieldUsername;
    private javax.swing.JButton jButtonRegister;
    private javax.swing.JButton jButtonToLogin;
    private javax.swing.JComboBox<String> jComboBoxRole;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelConfirmPassword;
    private javax.swing.JLabel jLabelPassword;
    private javax.swing.JLabel jLabelRole;
    private javax.swing.JLabel jLabelTelepon;
    private javax.swing.JLabel jLabelUsername;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JTextField jTextFieldTelepon;
    private javax.swing.JTextField jTextFieldUsername;
    // End of variables declaration//GEN-END:variables
}
