
package View;

import Model.TransaksiModel;
import java.util.Date;


public class Transaksi extends javax.swing.JFrame {

    private final TransaksiModel transaksiModel;
    private final MediaPlayer mediaPlayer;
    

    /**
     * Creates new form Transaksi
     * @param transaksiModel
     */
    public Transaksi(TransaksiModel transaksiModel, MediaPlayer mediaPlayer) {
        initComponents();
        this.transaksiModel = transaksiModel;
        this.mediaPlayer = mediaPlayer;
        displayData();
    }

    private void displayData() {
        // Menampilkan data transaksi pada label-label yang sesuai
        jLabelTanggal.setText("Tanggal Transaksi: " + transaksiModel.getTanggalTransaksi());
        jLabelUsername.setText("Username: " + transaksiModel.getUsername());
        jLabelDurasi.setText("Durasi: " + transaksiModel.getDurasi() + " jam");
        jLabelTotalHarga.setText("Total Harga: " + transaksiModel.getTotalHarga());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabelTanggal = new javax.swing.JLabel();
        jLabelUsername = new javax.swing.JLabel();
        jLabelDurasi = new javax.swing.JLabel();
        jLabelTotalHarga = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("TRANSAKSI");

        jLabelTanggal.setText("Tanggal Transaksi:");

        jLabelUsername.setText("Username:");

        jLabelDurasi.setText("Durasi:");

        jLabelTotalHarga.setText("Total Harga:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelTanggal)
                    .addComponent(jLabel1)
                    .addComponent(jLabelUsername)
                    .addComponent(jLabelDurasi)
                    .addComponent(jLabelTotalHarga))
                .addContainerGap(280, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelTanggal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelUsername)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelDurasi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelTotalHarga)
                .addContainerGap(178, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

        /**
         * @param args the command line arguments
         */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelDurasi;
    private javax.swing.JLabel jLabelTanggal;
    private javax.swing.JLabel jLabelTotalHarga;
    private javax.swing.JLabel jLabelUsername;
    // End of variables declaration//GEN-END:variables
}
