/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Model.TransaksiModel;

/**
 *
 * @author LENOVO
 */
public class Transaksi extends javax.swing.JFrame {

    private final TransaksiModel transaksiModel;

    /**
     * Creates new form Transaksi
     */
    public Transaksi(TransaksiModel transaksiModel) {
        initComponents();
        this.transaksiModel = transaksiModel;
        displayData();
    }

    private void displayData() {
        // Menampilkan data transaksi pada label-label yang sesuai
//        jLabelTanggal.setText("Tanggal Transaksi: " + transaksiModel.getTanggalTransaksi());
//        jLabelUsername.setText("Username: " + transaksiModel.getUsername());
//        jLabelDurasi.setText("Durasi: " + transaksiModel.getDurasi() + " jam");
//        jLabelTotalHarga.setText("Total Harga: " + transaksiModel.getTotalHarga());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabelTanggal = new javax.swing.JLabel();
        jLabelUsername = new javax.swing.JLabel();
        jLabelDurasi = new javax.swing.JLabel();
        jLabelTotalHarga = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1080, 608));
        setPreferredSize(new java.awt.Dimension(1080, 608));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setText("TRANSAKSI");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(24, 18, 62, 16);

        jLabelTanggal.setText("Tanggal Transaksi:");
        getContentPane().add(jLabelTanggal);
        jLabelTanggal.setBounds(24, 40, 97, 16);

        jLabelUsername.setText("Username:");
        getContentPane().add(jLabelUsername);
        jLabelUsername.setBounds(24, 62, 55, 16);

        jLabelDurasi.setText("Durasi:");
        getContentPane().add(jLabelDurasi);
        jLabelDurasi.setBounds(24, 84, 36, 16);

        jLabelTotalHarga.setText("Total Harga:");
        getContentPane().add(jLabelTotalHarga);
        jLabelTotalHarga.setBounds(24, 106, 66, 16);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/images/backgroundImage.png"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 340, 600, 270);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/images/backgroundImage.png"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(600, 350, 480, 260);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/images/backgroundImage.png"))); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(0, 0, 600, 340);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/images/backgroundImage.png"))); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(600, 0, 480, 340);

        pack();
    }// </editor-fold>//GEN-END:initComponents

        /**
         * @param args the command line arguments
         */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabelDurasi;
    private javax.swing.JLabel jLabelTanggal;
    private javax.swing.JLabel jLabelTotalHarga;
    private javax.swing.JLabel jLabelUsername;
    // End of variables declaration//GEN-END:variables
}
